

title: Anshruta Thakur 


description: >
  <div style="background: linear-gradient(135deg, #f6d365 0%, #fda085 100%); padding: 15px; border-radius: 10px;">
    <h2 style="font-family: 'Arial', sans-serif; color: #333;">As a data-driven Quantitative Analyst with a strong foundation from UCLA, I specialize in leveraging advanced data analytics and machine learning to drive significant financial decisions and strategy developments.</h2>
    <p style="font-family: 'Arial', sans-serif; color: #555;">
      My achievements include leveraging complex data sets at Optimas Capital to outperform benchmarks by 17.8% and developing a robust Forex trading strategy using sentiment analysis. I am skilled in Python, SQL, data visualization (Tableau), machine learning and predictive modeling, making me well-equipped to transform complex data into actionable insights and strategic guidance.
    </p>
    <br><br>
    <a href="https://www.linkedin.com/in/anshruta-thakur/" target="_blank" style="text-decoration: none;">
      <button style="background-color: #0072b1; color: white; border: none; padding: 10px 20px; border-radius: 5px;">View My LinkedIn Profile</button>
    </a>
    <br><br>
    <a href="https://anshrutathakur13.medium.com/" target="_blank" style="text-decoration: none;">
      <button style="background-color: #000; color: white; border: none; padding: 10px 20px; border-radius: 5px;">Visit My Medium</button>
    </a>
  </div>





