title: "<span style='color:#b19cd9;'>Anshruta Thakur</span>" # your name here, with pastel color styling
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  I love data. I love uncovering the stories it tells and turning those stories into actionable insights.
  <br><br>
  <strong>Experiences:</strong>
  <ul>
    <li>Founder & Mentor - Data Gals Initiative</li>
    <li>Data Science Intern, Real Estate Practice - ABGi USA</li>
    <li>Quantitative Analyst - Optimas Capital</li>
    <li>Data Analyst - Equity Methods LLC</li>
  </ul>
  <br>
  <strong>Leadership:</strong>
  <ul>
    <li>Consultant - 180 Degrees Consulting</li>
    <li>General Secretary - Women's Development Cell (Undergraduate University)</li>
  </ul>
  <br> #<br>
  <a href="https://www.linkedin.com/in/anshruta-thakur/" target="_blank" style="color:#6a0dad;">
   <img src="images/LinkedIn_icon.svg.png" alt="LinkedIn" style="width:50px;height:40px;margin-right:5px;">
   View My LinkedIn
  </a>
  <br><br>
  <a href="https://anshrutathakur13.medium.com/" target="_blank" style="color:#6a0dad;">
   <img src="images/1712115722819.jpeg" alt="Medium" style="width:60px;height:50px;margin-right:5px;">
   Visit My Medium
  </a>
  <br><br>
  <a href="https://your-data-gals-link.com" target="_blank" style="color:#6a0dad;">
   <img src="images/LinkedIn_Post.png" alt="Data Gals" style="width:60px;height:50px;margin-right:5px;">
   Visit Data Gals
  </a>
  <br><br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme



# google_analytics: UA-000000-0 # your Google Analytics tracking ID here

