title: Anshruta Thakur # your name (or website title) here
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  Data Science Intern at ABGi USA with a strong background in Quantitative Economics from UCLA. Passionate about using analytics to drive insights and decision-making.
  <br><br>
  **Experiences:**
  - Founder & Mentor - Data Gals Initiative
  - Data Science Intern - ABGi USA
  - Quantitative Analyst - Optimas Capital
  - Data Analyst - Equity Methods LLC
  - Researcher - UCLA Applied Business Project
  <br><br>
  <a href="https://www.linkedin.com/in/anshruta-thakur/" target="_blank">
   <img src="images/LinkedIn_icon.svg.png" alt="LinkedIn" style="width:50px;height:40px;margin-right:5px;">
   View My LinkedIn Profile
  </a>
  <br><br>
  <a href="https://anshrutathakur13.medium.com/" target="_blank">
   <img src="images/1712115722819.jpeg" alt="Medium" style="width:60px;height:50px;margin-right:5px;">
   Visit My Medium
  </a>
  <br><br>
remote_theme: pages-themes/midnight@v0.2.0
#pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# google_analytics: UA-000000-0 # your Google Analytics tracking ID here

