
title: Anshruta Thakur

description: >
  <div style="display: flex; flex-direction: column; justify-content: space-between; padding: 40px; margin: 20px 0; background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%); border-radius: 10px; width: 85%; line-height: 1.6; font-size: 16px;">
    <h2 style="font-family: 'Arial', sans-serif; color: #333; font-size: 24px;">Data Science and Economics Professional with a proven track record of delivering actionable insights and impactful strategies.</h2>
    <p style="font-family: 'Arial', sans-serif; color: #555; font-size: 18px;">I excel in leveraging advanced analytics, machine learning, and domain expertise to solve complex business problems and drive financial growth.</p>
    <br>
    <div style="display: flex; justify-content: center;">
      <a href="https://www.linkedin.com/in/anshruta-thakur/" target="_blank" style="text-decoration: none;">
        <button style="background-color: #0073b1; color: white; border: none; padding: 12px 24px; border-radius: 5px; font-size: 16px; margin-right: 10px;">View My LinkedIn Profile</button>
      </a>
      <a href="https://anshrutathakur13.medium.com/" target="_blank" style="text-decoration: none;">
        <button style="background-color: #333; color: white; border: none; padding: 12px 24px; border-radius: 5px; font-size: 16px;">Visit My Medium</button>
      </a>
    </div>
  </div>
remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme


