title: Anshruta Thakur
description: >
  <div style="display: flex; justify-content: space-between; height: 100vh; overflow: hidden;">
    <!-- Left Side: Introduction, Experience, Skills, and Tools -->
    <div style="width: 30%; padding: 20px; background: #f5f7fa; border-radius: 10px; overflow-y: auto;">
      <h2 style="font-family: 'Arial', sans-serif; color: #333; text-align: center;">Anshruta Thakur</h2>
      <p style="font-family: 'Arial', sans-serif; color: #555; font-size: 18px; line-height: 1.6;">
        Data Science and Economics Professional with a proven track record of delivering actionable insights and impactful strategies.
      </p>
      <p style="font-family: 'Arial', sans-serif; color: #555; font-size: 16px;">
        I excel in leveraging advanced analytics, machine learning, and domain expertise to solve complex business problems and drive financial growth.
      </p>
      <div style="text-align: center; margin: 20px 0;">
        <a href="https://www.linkedin.com/in/anshruta-thakur/" target="_blank" style="text-decoration: none;">
          <button style="background-color: #0073b1; color: white; border: none; padding: 12px 24px; border-radius: 5px; font-size: 16px; margin-right: 10px;">View My LinkedIn Profile</button>
        </a>
        <a href="https://anshrutathakur13.medium.com/" target="_blank" style="text-decoration: none;">
          <button style="background-color: #333; color: white; border: none; padding: 12px 24px; border-radius: 5px; font-size: 16px;">Visit My Medium</button>
        </a>
      </div>

      <!-- Experience, Skills, and Tools -->
      <h3 style="font-family: 'Arial', sans-serif; color: #333;">Experience</h3>
      <ul style="font-family: 'Arial', sans-serif; color: #555; font-size: 16px;">
        <li>Quantitative Analyst at Optimas Capital</li>
        <li>Data Science Intern at ABGi USA</li>
        <li>Data Analyst at Equity Methods LLC</li>
      </ul>

      <h3 style="font-family: 'Arial', sans-serif; color: #333; margin-top: 20px;">Skills</h3>
      <ul style="font-family: 'Arial', sans-serif; color: #555; font-size: 16px;">
        <li>Python, SQL, R</li>
        <li>Machine Learning, NLP</li>
        <li>Data Visualization (Tableau, Power BI)</li>
        <li>Predictive Modeling</li>
        <li>Statistical Analysis</li>
      </ul>

      <h3 style="font-family: 'Arial', sans-serif; color: #333; margin-top: 20px;">Tools & Technologies</h3>
      <ul style="font-family: 'Arial', sans-serif; color: #555; font-size: 16px;">
        <li>Google Cloud, AWS</li>
        <li>Power BI, Tableau</li>
        <li>Git, GitHub</li>
      </ul>
    </div>

    <!-- Right Side: Portfolio Projects -->
    <div style="width: 65%; padding: 20px; overflow-y: auto;">
      <h2>Portfolio</h2>
      <div class="project-cards">
        <div class="card" style="margin-bottom: 20px;">
          <h3>ML Models for Quantitative Finance- Alpha Research</h3>
          <p>At Optimas Capital, a distinguished investment management firm, I analyzed a complex dataset with over 2000 financial features using PCA and machine learning models like Random Forest and XGBoost, developing strategies that outperformed the market benchmark by 17.8%.</p>
          <button onclick="window.location.href='https://github.com/athk13/Quantitative-Finance-ML-Model';" style="background-color: #333; color: white; border: none; padding: 10px 20px; border-radius: 5px;">View project on GitHub</button>
        </div>
        
        <div class="card" style="margin-bottom: 20px;">
          <h3>Sentiment Analysis- Forex Trading Strategy</h3>
          <p>In this project, I developed a Forex trading strategy by conducting sentiment analysis on economic news extracted using the NY Times API, spanning 2003 to 2024, using advanced NLP techniques and machine learning algorithms. The strategy was optimized through backtesting and hyperparameter tuning, achieving a 1.4% annualized return.</p>
          <button onclick="window.location.href='https://github.com/athk13/FX-Sentiment-Analysis-Trading-Strategy';" style="background-color: #333; color: white; border: none; padding: 10px 20px; border-radius: 5px;">View project on GitHub</button>
        </div>

        <div class="card" style="margin-bottom: 20px;">
          <h3>Deep NLP- Hate Speech Recognition</h3>
          <p>This project involves developing a machine learning model to detect hateful and offensive speech on social media platforms, specifically analyzing tweets from the 2020 US Elections using BERT and other NLP techniques.</p>
          <button onclick="window.location.href='https://colab.research.google.com/drive/1rRiavPZYeSQPbQE0IoRFXuawqtjPFXta?usp=sharing';" style="background-color: #333; color: white; border: none; padding: 10px 20px; border-radius: 5px;">View project on Colab</button>
          <button onclick="window.location.href='https://anshrutathakur13.medium.com/decoding-discord-using-ai-to-identify-hate-speech-100e8073d3bf';" style="background-color: #333; color: white; border: none; padding: 10px 20px; border-radius: 5px; margin-left: 10px;">View article on Medium</button>
        </div>
      </div>
    </div>
  </div>



