title: Anshruta Thakur
description: >
  <div style="display: flex; justify-content: space-between; height: 100vh; overflow: hidden;">
    <!-- Left Side: Introduction, Experience, Skills, and Tools -->
    <div style="width: 30%; padding: 20px; background: #f5f7fa; border-radius: 10px; overflow-y: auto;">
      <h2 style="font-family: 'Arial', sans-serif; color: #333; text-align: center;">Anshruta Thakur</h2>
      <p style="font-family: 'Arial', sans-serif; color: #555; font-size: 18px; line-height: 1.6;">
        Data Science and Economics Professional with a proven track record of delivering actionable insights and impactful strategies.
      </p>
      <p style="font-family: 'Arial', sans-serif; color: #555; font-size: 16px;">
        I excel in leveraging advanced analytics, machine learning, and domain expertise to solve complex business problems and drive financial growth.
      </p>
      <div style="text-align: center; margin: 20px 0;">
        <a href="https://www.linkedin.com/in/anshruta-thakur/" target="_blank" style="text-decoration: none;">
          <button style="background-color: #0073b1; color: white; border: none; padding: 12px 24px; border-radius: 5px; font-size: 16px; margin-right: 10px;">View My LinkedIn Profile</button>
        </a>
        <a href="https://anshrutathakur13.medium.com/" target="_blank" style="text-decoration: none;">
          <button style="background-color: #333; color: white; border: none; padding: 12px 24px; border-radius: 5px; font-size: 16px;">Visit My Medium</button>
        </a>
      </div>

      <!-- Experience, Skills, and Tools -->
      <h3 style="font-family: 'Arial', sans-serif; color: #333;">Experience</h3>
      <ul style="font-family: 'Arial', sans-serif; color: #555; font-size: 16px;">
        <li>Quantitative Analyst at Optimas Capital</li>
        <li>Data Science Intern at ABGi USA</li>
        <li>Data Analyst at Equity Methods LLC</li>
      </ul>

      <h3 style="font-family: 'Arial', sans-serif; color: #333; margin-top: 20px;">Skills</h3>
      <ul style="font-family: 'Arial', sans-serif; color: #555; font-size: 16px;">
        <li>Python, SQL, R</li>
        <li>Machine Learning, NLP</li>
        <li>Data Visualization (Tableau, Power BI)</li>
        <li>Predictive Modeling</li>
        <li>Statistical Analysis</li>
      </ul>

      <h3 style="font-family: 'Arial', sans-serif; color: #333; margin-top: 20px;">Tools & Technologies</h3>
      <ul style="font-family: 'Arial', sans-serif; color: #555; font-size: 16px;">
        <li>Google Cloud, AWS</li>
        <li>Power BI, Tableau</li>
        <li>Git, GitHub</li>
      </ul>
    </div>

    
    </div>
  </div>



