title: "<span style='color:#b19cd9;'>Anshruta Thakur</span>" # your name here, with pastel color styling

# Description section with timeline-like experience format
description: > 
  I love data. I love uncovering the stories it tells and turning those stories into actionable insights.
  <br><br>
  <strong>Experiences:</strong>

  <div style="position: relative; max-width: 800px; margin: 0 auto; padding: 10px 0;"> <!-- Reduced padding -->
    
    <!-- Experience 1 -->
    <div style="padding: 10px 0; position: relative;"> <!-- Reduced padding -->
      <div style="font-weight: bold; color: #b19cd9; float: left; width: 30%; text-align: right; padding-right: 15px; font-size: 0.9em;"> <!-- Increased width and reduced font size -->
        Sep 2024 - Present
      </div>
      <div style="padding-left: 35px; border-left: 2px solid #b19cd9; position: relative;"> <!-- Adjusted padding -->
        <h3>Founder & Mentor - Data Gals Initiative</h3>
      </div>
    </div>

    <!-- Experience 2 -->
    <div style="padding: 10px 0; position: relative;"> <!-- Reduced padding -->
      <div style="font-weight: bold; color: #b19cd9; float: left; width: 30%; text-align: right; padding-right: 15px; font-size: 0.9em;"> <!-- Increased width and reduced font size -->
        Jun 2024 - Present
      </div>
      <div style="padding-left: 35px; border-left: 2px solid #b19cd9; position: relative;"> <!-- Adjusted padding -->
        <h3>Data Science Intern, Real Estate Practice - ABGi USA</h3>
      </div>
    </div>

    <!-- Experience 3 -->
    <div style="padding: 10px 0; position: relative;"> <!-- Reduced padding -->
      <div style="font-weight: bold; color: #b19cd9; float: left; width: 30%; text-align: right; padding-right: 15px; font-size: 0.9em;"> <!-- Increased width and reduced font size -->
        Jan 2024 - Mar 2024
      </div>
      <div style="padding-left: 35px; border-left: 2px solid #b19cd9; position: relative;"> <!-- Adjusted padding -->
        <h3>Quantitative Analyst - Optimas Capital</h3>
      </div>
    </div>

    <!-- Experience 4 -->
    <div style="padding: 10px 0; position: relative;"> <!-- Reduced padding -->
      <div style="font-weight: bold; color: #b19cd9; float: left; width: 30%; text-align: right; padding-right: 15px; font-size: 0.9em;"> <!-- Increased width and reduced font size -->
        Aug 2023 - Sep 2023
      </div>
      <div style="padding-left: 35px; border-left: 2px solid #b19cd9; position: relative;"> <!-- Adjusted padding -->
        <h3>Data Analyst - Equity Methods LLC</h3>
      </div>
    </div>

  </div>

  <a href="https://www.linkedin.com/in/anshruta-thakur/" target="_blank" style="color:#6a0dad;">
    <img src="images/LinkedIn_icon.svg.png" alt="LinkedIn" style="width:50px;height:40px;margin-right:5px;">
    View My LinkedIn
  </a>
  <br><br>
  <a href="https://anshrutathakur13.medium.com/" target="_blank" style="color:#6a0dad;">
    <img src="images/1712115722819.jpeg" alt="Medium" style="width:60px;height:50px;margin-right:5px;">
    Visit My Medium
  </a>
  <br><br>
  <a href="https://datagals.notion.site/Data-Gals-Initiative-42992f48c28545e89f2a18802ce5d716?p=5385d7dddaa245f78271895f533d2d70&pm=c" target="_blank" style="color:#6a0dad;">
    <img src="images/LinkedIn_Post.png" alt="Data Gals" style="width:60px;height:50px;margin-right:5px;">
    Visit Data Gals
  </a>
  <br><br>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme





# google_analytics: UA-000000-0 # your Google Analytics tracking ID here

